DROP TABLE IF EXISTS Movimento;

CREATE TABLE Movimento (
	MovID INTEGER PRIMARY KEY,
	MovData INTEGER NOT NULL,
	MovBarra TEXT NOT NULL,
	MovSentido TEXT NOT NULL,
	MovBloqueado INTEGER DEFAULT 0 NOT NULL,
	MovForaHorario INTEGER DEFAULT 0 NOT NULL,
	MovProvisorio INTEGER DEFAULT 0 NOT NULL,
	UsrCodigo INTEGER,
	FOREIGN KEY(UsrCodigo) REFERENCES Usuario(UsrCodigo)
);
